export const techs = [
    {
        name:'React',
        iconName:'react'
    },
    {
        name:'GIT',
        iconName:'git'
    },
    {
        name:'Python',
        iconName:'python'
    },
    {
        name:'JS',
        iconName:'javascript'
    },
    {
        name:'Node',
        iconName:'nodejs'
    },
    {
        name:'Redis',
        iconName:'redis'
    },
    {
        name:'MongoDB',
        iconName:'mongodb'
    },
    {
        name:'VSCode',
        iconName:'visualstudio'
    },
    {
        name:'BootStrap',
        iconName:'bootstrap'
    },
    {
        name:'HTML5',
        iconName:'html5'
    },
    {
        name:'CSS3',
        iconName:'css3'
    }
]